import Foundation

/// A popular service with a bundled logo. The catalog lives in
/// `KnownService+Catalog.swift`, generated by `Scripts/generate_services.py`.
///
/// Matching is done entirely offline against the bundled list; the app
/// never fetches icons from the network.
struct KnownService: Identifiable, Hashable {
    let id: String
    let name: String
    let domains: [String]
    enum Logo {
        /// Single-color mark (Simple Icons), drawn in white or black on the brand color.
        case monochrome
        /// Full-color mark (gilbarbara/logos), drawn as-is on a white tile.
        case color
        /// No bundled logo; shows the first letter on the brand color.
        case none
    }

    /// Brand color as 0xRRGGBB.
    let color: UInt32
    let logo: Logo

    var logoAssetName: String? { logo == .none ? nil : "service-\(id)" }
    var website: String { "https://\(domains[0])" }

    /// The service for a login: by website first, then by exact title
    /// (so migrated items with only a name, like "GitHub", still match).
    static func matching(_ item: LoginItem) -> KnownService? {
        for website in item.websites {
            if let service = matching(website: website) { return service }
        }
        let title = item.title.trimmed
        return all.first { $0.name.caseInsensitiveCompare(title) == .orderedSame }
    }

    /// Matches a host or any subdomain of it. When several domains match,
    /// the most specific wins, so mail.google.com is Gmail rather than Google.
    static func matching(website: String) -> KnownService? {
        guard let normalized = LoginValidation.normalizedWebsite(website),
              var host = URL(string: normalized)?.host()?.lowercased()
        else { return nil }
        if host.hasPrefix("www.") { host.removeFirst(4) }

        var best: (service: KnownService, length: Int)?
        for service in all {
            for domain in service.domains where host == domain || host.hasSuffix("." + domain) {
                if domain.count > best?.length ?? 0 { best = (service, domain.count) }
            }
        }
        return best?.service
    }

    static func search(_ query: String) -> [KnownService] {
        let query = query.trimmed
        let sorted = all.sorted { $0.name.localizedStandardCompare($1.name) == .orderedAscending }
        guard !query.isEmpty else { return sorted }
        return sorted.filter { service in
            service.name.localizedStandardContains(query)
                || service.domains.contains { $0.localizedStandardContains(query) }
        }
    }
}

extension SignInMethod {
    /// The service whose logo represents this method; nil for "not set" and
    /// for plain email/username & password.
    var service: KnownService? {
        let id: String? = switch self {
        case .notSet, .standard: nil
        case .google: "google"
        case .apple: "apple"
        case .microsoft: "microsoft"
        case .github: "github"
        case .facebook: "facebook"
        case .twitter: "x"
        case .linkedin: "linkedin"
        case .discord: "discord"
        }
        return id.flatMap { id in KnownService.all.first { $0.id == id } }
    }
}
