// Exports the service catalog and logos from the macOS app to the Android app,
// so both show the same services. Run from the repository root after
// Scripts/generate_services.py has updated the Mac catalog:
//
//   swift Scripts/export_android_services.swift
//
// Reads:  SyncedPass/Models/KnownService+Catalog.swift
//         SyncedPass/Assets.xcassets/Services/*.imageset
// Writes: android/app/src/main/java/.../model/KnownServiceCatalog.kt
//         android/app/src/main/res/drawable-nodpi/service_*.png
//
// Logos are rasterized with AppKit (which draws SVG natively) at 128 px on
// their longest side: sharp at the sizes Android shows them (up to 48 dp).

import AppKit

let catalogPath = "SyncedPass/Models/KnownService+Catalog.swift"
let assetsPath = "SyncedPass/Assets.xcassets/Services"
let kotlinPath = "android/app/src/main/java/com/abdurahmanharouat/syncedpass/model/KnownServiceCatalog.kt"
let drawablePath = "android/app/src/main/res/drawable-nodpi"
let maxSide: CGFloat = 128

struct Service {
    let id, name: String
    let domains: [String]
    let color: String
    let logo: String
}

let pattern = #"KnownService\(id: "([^"]+)", name: "([^"]+)", domains: \[([^\]]*)\], color: 0x([0-9A-Fa-f]{6}), logo: \.(\w+)\)"#
let source = try String(contentsOfFile: catalogPath, encoding: .utf8)
let regex = try NSRegularExpression(pattern: pattern)
let services: [Service] = regex.matches(in: source, range: NSRange(source.startIndex..., in: source)).map { match in
    let group = { (i: Int) -> String in String(source[Range(match.range(at: i), in: source)!]) }
    let domains: [String] = group(3).split(separator: ",").map { part in
        part.trimmingCharacters(in: CharacterSet(charactersIn: " \""))
    }
    return Service(id: group(1), name: group(2), domains: domains, color: group(4).uppercased(), logo: group(5))
}
guard !services.isEmpty else { fatalError("No services found in \(catalogPath)") }

/// Android resource names allow only a-z, 0-9 and _.
func resourceName(_ id: String) -> String {
    "service_" + id.lowercased().map { $0.isLetter || $0.isNumber ? String($0) : "_" }.joined()
}

func render(_ image: NSImage, to path: String) throws {
    let scale = maxSide / max(image.size.width, image.size.height)
    let width = Int((image.size.width * scale).rounded()), height = Int((image.size.height * scale).rounded())
    guard let bitmap = NSBitmapImageRep(bitmapDataPlanes: nil, pixelsWide: width, pixelsHigh: height, bitsPerSample: 8,
                                        samplesPerPixel: 4, hasAlpha: true, isPlanar: false, colorSpaceName: .deviceRGB,
                                        bytesPerRow: 0, bitsPerPixel: 0) else { fatalError("bitmap") }
    NSGraphicsContext.saveGraphicsState()
    NSGraphicsContext.current = NSGraphicsContext(bitmapImageRep: bitmap)
    NSGraphicsContext.current?.imageInterpolation = .high
    image.draw(in: NSRect(x: 0, y: 0, width: width, height: height))
    NSGraphicsContext.restoreGraphicsState()
    try bitmap.representation(using: .png, properties: [:])!.write(to: URL(filePath: path))
}

// Remove logos of services that were dropped from the catalog.
let fm = FileManager.default
for file in try fm.contentsOfDirectory(atPath: drawablePath) where file.hasPrefix("service_") {
    try fm.removeItem(atPath: "\(drawablePath)/\(file)")
}

var entries: [String] = []
for service in services {
    var logoRef = "null"
    if service.logo != "none" {
        let folder = "\(assetsPath)/service-\(service.id).imageset"
        guard let file = try fm.contentsOfDirectory(atPath: folder).first(where: { $0.hasSuffix(".svg") || $0.hasSuffix(".png") }),
              let image = NSImage(contentsOfFile: "\(folder)/\(file)")
        else { fatalError("No logo for \(service.id)") }
        try render(image, to: "\(drawablePath)/\(resourceName(service.id)).png")
        logoRef = "R.drawable.\(resourceName(service.id))"
    }
    let kind = ["monochrome": "Monochrome", "color": "Color", "appIcon": "AppIcon", "none": "None"][service.logo]!
    let domains = service.domains.map { "\"\($0)\"" }.joined(separator: ", ")
    entries.append("    KnownService(\"\(service.id)\", \"\(service.name)\", listOf(\(domains)), 0x\(service.color), Logo.\(kind), \(logoRef)),")
}

let kotlin = """
// Generated by Scripts/export_android_services.swift from the macOS catalog — do not edit by hand.

package com.abdurahmanharouat.syncedpass.model

import com.abdurahmanharouat.syncedpass.R
import com.abdurahmanharouat.syncedpass.model.KnownService.Logo

internal val knownServiceCatalog: List<KnownService> = listOf(
\(entries.joined(separator: "\n"))
)

"""
try kotlin.write(toFile: kotlinPath, atomically: true, encoding: .utf8)
print("Exported \(services.count) services, \(entries.filter { !$0.hasSuffix("null),") }.count) logos.")
